### ISSUE TITLE
not supoort os x?

### ISSUE THREAD

**Issue by r0zero** [OffensivePython/Nscan#1]
when i will try install nscan on os x，i use python nscan.py
it is wrong，except：
Traceback (most recent call last):
  File "nscan.py", line 114, in <module>
    options = parser.parse_args()
  File "Nscan/nscan/startup.py", line 44, in parse_args
    ifname, ifaddr, ifmac, gateway = get.Network()
  File "Nscan/nscan/get.py", line 80, in Network
    sniff = socket.socket(socket.AF_PACKET,
AttributeError: 'module' object has no attribute 'AF_PACKET'

use google search i found Some people encounter this problem，url：
http://bb.secdev.org/scapy/issue/174/sniffing-loopback-in-mac-os-x-darwin
pls solve。

**Comment by OffensivePython** [comment]
OS X doesn't support raw sockets

**Comment by r0zero** [comment]
thx，i will try linux
