### ISSUE TITLE
Can't detect interfaces

### ISSUE THREAD

**Issue by DarkRedman** [OffensivePython/Nscan#3]
It seems the program scan on the wrong place on Arch Linux I got this error
`IOError: [Errno 2] No such file or directory: '/etc/network/interfaces'`

It should rather check in /sys/class/net for arch linux

**Comment by OffensivePython** [comment]
I need to setup Arch Linux VM and figure out what causes the error. Do you have any solution for now?

**Comment by archey** [comment]
The error is mainly cause by the fact that if /etc/network/interfaces does not exist the script crashes as it tries to create a device or add a device to /etc/network/interfaces which does not exist on archlinux. It would be nice if this was more OS agnostic.

**Comment by OffensivePython** [comment]
How can we fix this for now?

**Comment by DarkRedman** [comment]
Honestly I've no idea.

**Comment by go-spider** [comment]
centos -->/etc/sysconfig/network
