### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by alexjj** [OffensivePython/Nscan#4]
Following the first steps (git clone, chmod +x etc.) then running with `./nscan.py` gives the error:

```
File "./nscan.py", line 114
print LOGO
         ^
SyntaxError: Missing parentheses in call to 'print'`
```

**Comment by OffensivePython** [comment]
What Python version do you use?

**Comment by alexjj** [comment]
Python 2.7.9

On 5 February 2015 at 14:03, OffensivePython notifications@github.com
wrote:

> What Python version do you use?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OffensivePython/Nscan/issues/4#issuecomment-73139747.

## 

Alex Johnstone
B2452245

**Comment by OffensivePython** [comment]
Add a parentheses to each print call:
print(LOGO)
