### ISSUE TITLE
why need load iface?

### ISSUE THREAD

**Issue by hleiz** [OffensivePython/Nscan#7]
I have read the source code for several days.
why we need load iface? I have google for reason but not find,

code:
iface = dec2dot(self.ifaddr+1)        the addr is +1,so i have ifconfig like

eth0      Link encap:Ethernet  HWaddr 00:0c:29:8e:ab:ac  
          inet addr:192.168.128.131  Bcast:192.168.128.255  Mask:255.255.255.0

eth0:nscan0 Link encap:Ethernet  HWaddr 00:0c:29:8e:ab:ac  
          inet addr:192.168.128.132  Bcast:192.168.128.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

but if I am not inter network, a public ip addr , +1 will not a exist ip,am i right?

so ...pls help..

**Comment by OffensivePython** [comment]
This issue is fixed in the latest version: https://github.com/OffensivePython/Nscan

**Comment by hleiz** [comment]
i have run the latest version and read the source ,need i load iface?
eth0      Link encap:Ethernet  HWaddr 00:0c:29:8e:ab:ac  
          inet addr:192.168.128.131  Bcast:192.168.128.255  Mask:255.255.255.0
          inet6 addr: fe80::20c:29ff:fe8e:abac/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:288 errors:0 dropped:0 overruns:0 frame:0
          TX packets:108 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:93375 (91.1 KiB)  TX bytes:11249 (10.9 KiB)

eth0:nscan0 Link encap:Ethernet  HWaddr 00:0c:29:8e:ab:ac  
          inet addr:192.168.128.132  Bcast:192.168.128.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1

can i use 192.168.128.131 for scan? not use 132(not load iface)?

**Comment by OffensivePython** [comment]
follow the steps described in the readme file.

**Comment by hleiz** [comment]
Sorry, probably I didn't explain it clear enough and caused your misunderstanding
i have read the readme file :If this your first run, you need to load nscan alias interface before launching a Scan

what i just want know is why we need to load nscan alias interface? if not load ,i think it will work fine?

btw: the latest version not work in my kali linux,i have read the source ,it will load iface at the first time auto(also i run python nscan iface load,same error). when i run ,error cause:  
File "/root/Nscan/latest/probe.py", line 186, in send
    sock.sendto(packet, (dec2dot(target), 0)) # self.ifname
error: [Errno 19] No such device.  
 i think its a bug,but i am not care.

**Comment by OffensivePython** [comment]
You should always load the interface: ./nscan.py iface load
other than that, if you have ethernet or wifi interfaces, you better use the stable version:
https://github.com/OffensivePython/Nscan/tree/master/stable

**Comment by hleiz** [comment]
yes, i use the stable version,its success.
but i want know why i need load the interface?
what is the reason for this realization?

**Comment by go-spider** [comment]
have you resolve this?error: [Errno 19] No such device
